### PR TITLE
FOLIO-2904 node script to purge loan data

### PR DESCRIPTION
**Pull request by zburke**
`index.js` node script performs the following actions:

1. check in all outstanding loans (this will clear patron blocks due to
   items aged to lost; it will also generate lots of fee/fines records)
2. transfer all outstanding fee/fine records (this will close all open fee/fines)
3. cancel all Page requests with request status Open- Not yet filled
4. anonymize all closed loans
5. delete all closed fee/fines

HTTP request handling is abstracted in `okapi-request`.

Refs [FOLIO-2904](https://issues.folio.org/browse/FOLIO-2904)

### CODE REVIEW

**Review by doytch — COMMENTED** [review]
This is nice! Also a good reminder that this repo exists. I'll keep it in mind when I write similar tools for Duke.

**Comment by zburke** [comment]
Thanks, @doytch! Is there a different/better way you think `OkapiRequest` (truly, the only thing I really wanted to call folks' attention to) should be provided, e.g. do you think it should be in a separate repo and published as a formal NPM module, maybe in/along side [stripes-cli](/folio-org/stripes-cli)?  

* +1 that's more official and correct in basically every possible way
* -1 that breaks the model of "no deps, no install, just do `node ./the-script.js`", but only scripts in this here repository enjoy that, so maybe that's a BS model anyway. 

The existing code was extracted from [add-users](/folio-org/folio-tools/tree/master/add-users/) with [STCLI-149](https://issues.folio.org/browse/STCLI-149) in mind.

**Comment by doytch** [comment]
I'm not sure... On the one hand, it'd be nice to just have it and be able to grab it, but the functionality is pretty slim and I didn't bat an eye writing it myself (with `axios` tho) when I needed it. Also, you'll probably have to build it out a bit more if you want to go that route. For example, I'd rather pass the username/password to my app as a filename (`--userFile folioUser.js` or whatever) so I'd probably want it to accept the configuration as an object as well as an array...

I don't really understand the goal of using no dependencies for what it's worth. It makes fetching complicated here, but even basic stuff like logging hurts if you can't in the future create a slim logger in another repo for your use. I ran into that when I realised that I wanted to write errors to a file, and colour-code warnings/errors/info, and automatically stringify JS structures...

**Review by mkuklis — APPROVED** [review]
Nice and clear @zburke! I had no idea folio-tools existed.

**Pull request merged**
